export const headingIconText = {
    aboutUs__headingIconText : "About us",
    houseCleaning__headingIconText : "House Cleaning",
    cleanAndFresh__headingIconText : "Clean and Fresh",
    weMakePepoleHappy__headingIconText : "We Make People Happy",
    trustedCleaning__headingIconText : "Trusted Cleaning",
    homeCleaning__headingIconText : "Home Cleaning",
    freeCleaning__headingIconText : "Free Non-Toxic Cleaning",
    enjoyableFreshly__headingIconText : "Enjoyable Freshly",
    professional__headingIconText : "Professional",
    residentialCleaning__headingIconText : "Residential Cleaning",
    commercialCleaning__headingIconText : "Commercial Cleaning",
    whyWeSpecial__headingIconText : "Why We Special",
    whyChooseUs__headingIconText : "Why Choose Us",
}